version: '3.4'

services:
  frontend:
    image: photoeditingai
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: .env.docker
    ports:
      - "3000:3000"
      - "8080:80"
      - "443:443"
    restart: "always"